
-- 銘柄基本情報
CREATE TABLE company_statistics (										
	symbol					VARCHAR(10)				,
	name					VARCHAR(50)				,
	exchange					VARCHAR(30)				,
	established_date					VARCHAR(10)				,
	listing_date					VARCHAR(10)				,
	sector					VARCHAR				,
	industry					VARCHAR				,
	ex_dividend_date					VARCHAR(10)				,
	dividend_yield					REAL				,
	present_price					NUMERIC				
	year_change_ratio					REAL				,
	year_low					NUMERIC				,
	year_high					NUMERIC				,
	book_value_per_share					NUMERIC				,
	per					REAL				,
	pbr					REAL				,
	eps					REAL				,
	roa					REAL				,
	roe					REAL				,
	debt_equity_ratio					REAL				,
	own_capital_ratio					REAL				,
	market_cap					REAL				,
	enterprise_value					REAL				,
	credit_multiplier					REAL				,
	moving_average_deviation					NUMERIC				,
	amount_of_sales					VARCHAR(10)				,
	net_income					VARCHAR(10)				,
	sales_cf					VARCHAR(10)				,
	total_assets					VARCHAR(10)				,
	cash_and_deposits					VARCHAR(10)				,
	total_capital					VARCHAR(10)				,
	average_annual_income					VARCHAR				,
	grade_rating					REAL				,
	index_adoption					VARCHAR				,
	business_scope					VARCHAR				,
	product_range					VARCHAR				,
	representative					VARCHAR				,
	capital_stock					VARCHAR				,
	address					VARCHAR				,
	tel					VARCHAR				,
	per_unit					VARCHAR				,
	url					VARCHAR				,
	delisting_date					VARCHAR(10)				,
	update_date					VARCHAR(10)				,
	PRIMARY KEY(symbol)
);										
